matrix:
  include:
  - language: node_js
    node_js: node
    before_install:
    - cd server
    install:
    - nvm install node
    - node -v
    - npm install
deploy:
  provider: script
  on: beta
  script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "$travis_ssh_private_key" > ~/.ssh/id_rsa
    - echo -e "$travis_ssh_public_key" > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa
    - git remote add heroku git@heroku.com:sdp-10-beta.git
    - git subtree push --prefix server heroku master
